### ISSUE TITLE
Mapcraft implementation

### ISSUE THREAD

**Issue by DLuminary** [Sachini/Fusion-DHL#1]
Hello,

Firstly, thank you for sharing your work (paper and code).
In it you state in regards to Mapcraft that the code is not publicly available, and that you implement it locally with few modifications to improve accuracy. Would it be possible to share this local implementation for reproduction of paper results and further comparison?

Many thanks in advance,

**Comment by Sachini** [comment]
Thank you for your interest.
Unfortunately we cannot share the code for this baseline
