### ISSUE TITLE
starting_params file: args.starting_variables

### ISSUE THREAD

**Issue by jhihcing0831** [Sachini/Fusion-DHL#2]
Hi,

Thank you for sharing your code.
I tried to run "optimizer.py". It seems that it lacks starting_variable file.
Could you share this file? Or how do I build this file?
The following code is for starting_variable:
parser.add_argument('--starting_variables', type=str,
                        help='Path to file containing optimization varibles (ensure same number of parameter)')

Many thanks in advance.

**Comment by Sachini** [comment]
It's an optional parameter and not required for usual execution
